//! Rust gRPC client for the Rclone IPC bridge (Section 13).
//!
//! This client talks to a Go process that embeds Rclone and exposes the
//! `RcloneBridge` service defined in proto/rclone_bridge.proto.
//!
//! The Go side is responsible for actually calling into Rclone's library
//! (do **not** reimplement Rclone logic here).

use crate::application::ports::CloudCredential;
use tonic::transport::Channel;

pub mod pb {
    // This will be generated by build.rs from proto/rclone_bridge.proto
    tonic::include_proto!("uniflow.rclone");
}

use pb::rclone_bridge_client::RcloneBridgeClient as PbClient;
use pb::*;

#[derive(Clone)]
pub struct RcloneBridgeClient {
    inner: PbClient<Channel>,
}

impl RcloneBridgeClient {
    /// Connect to a running Rclone bridge (e.g. "http://127.0.0.1:50051").
    pub async fn connect(endpoint: impl Into<String>) -> Result<Self, tonic::transport::Error> {
        let channel = Channel::from_shared(endpoint.into())
            .unwrap()
            .connect()
            .await?;
        Ok(Self {
            inner: PbClient::new(channel),
        })
    }

    /// Configure a remote with credentials (called before operations).
    pub async fn configure_remote(
        &mut self,
        name: &str,
        cred: CloudCredential,
    ) -> Result<ConfigureRemoteResponse, tonic::Status> {
        let request = ConfigureRemoteRequest {
            name: name.to_string(),
            credential: Some(Credential {
                provider: cred.provider,
                config: cred.config,
            }),
        };
        let response = self.inner.configure_remote(request).await?;
        Ok(response.into_inner())
    }

    /// Perform a copy (may use server-side if the bridge detects it).
    pub async fn copy(
        &mut self,
        src_remote: &str,
        src_path: &str,
        dst_remote: &str,
        dst_path: &str,
    ) -> Result<TransferResponse, tonic::Status> {
        let req = CopyRequest {
            src_remote: src_remote.to_string(),
            src_path: src_path.to_string(),
            dst_remote: dst_remote.to_string(),
            dst_path: dst_path.to_string(),
            create_dirs: true,
        };
        let resp = self.inner.copy(req).await?;
        Ok(resp.into_inner())
    }

    /// Explicit server-side copy (zero bandwidth when supported by the provider).
    pub async fn server_side_copy(
        &mut self,
        src_remote: &str,
        src_path: &str,
        dst_remote: &str,
        dst_path: &str,
    ) -> Result<TransferResponse, tonic::Status> {
        let req = ServerSideCopyRequest {
            src_remote: src_remote.to_string(),
            src_path: src_path.to_string(),
            dst_remote: dst_remote.to_string(),
            dst_path: dst_path.to_string(),
        };
        let resp = self.inner.server_side_copy(req).await?;
        Ok(resp.into_inner())
    }

    // Additional methods (multipart, range download, etc.) can be added here following the same pattern.
    // For a minimal Phase 1 implementation the copy / server_side_copy paths are sufficient
    // for the basic Local<->Cloud and Cloud<->Cloud (same provider) cases.
}